### ISSUE TITLE
使用DrawingManager绘制好的图形如何再此编辑

### ISSUE THREAD

**Issue by ReinhardChen93** [huiyan-fe/react-bmapgl#10]
使用DrawingManager绘制好的图形如何再此编辑

**Comment by Junior2Ran** [comment]
获取到overlay对象后，使用overlay.enableEditing()启用编辑

**Comment by ReinhardChen93** [comment]
![20210408150908](https://user-images.githubusercontent.com/43949619/113984029-39069a00-987d-11eb-936a-a27551e6ab47.png)
请问使用overlay.enableEditing()后,如何再次显示出这个操作栏来?
