### ISSUE TITLE
react-bmapgl无法使用BMapGL.Point

### ISSUE THREAD

**Issue by wenyu-yu** [huiyan-fe/react-bmapgl#11]
## 问题描述

想要实现地图的折线效果，但是根据文档发现react-bmapgl包里并没有BMapGL.Point相关方法：

文档地址：http://lbsyun.baidu.com/solutions/reactBmapDoc

截图：
![1](https://user-images.githubusercontent.com/49123717/104158715-e148c600-5428-11eb-801a-4cffe2921b2d.PNG)

源码截图：
![2](https://user-images.githubusercontent.com/49123717/104158739-ec035b00-5428-11eb-83ce-4eecd6d79a4d.PNG)

**Comment by Junior2Ran** [comment]
请阅读文档中 **开始使用** 部分内容。
引入脚本后就会有BMapGL的命名空间，也有BMapGL.Point类
`<script type="text/javascript" src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=您的密钥"></script>`

**Comment by wenyu-yu** [comment]
但是react文件里没有导入，打包会报错啊，我看类型定义文件里只有Map

**Comment by wenyu-yu** [comment]
但是react文件里没有导入，打包会报错啊，我看类型定义文件里只有Map
