### ISSUE TITLE
demo上的Arc动画没出来 

### ISSUE THREAD

**Issue by proto1994** [huiyan-fe/react-bmapgl#12]
"react-bmapgl": "^0.1.3",

` 

import { Map, CustomOverlay } from 'csr!react-bmapgl';

import Arc from 'csr!react-bmapgl/Custom/Arc';

 <Arc
          autoViewport={false}
          lineOptions={{
            width: 5,
            color: 'rgba(250, 50, 20, 0.7)'
          }}
          arrowOptions={{
            styleOptions: {
              color: 'rgba(250, 50, 20, 0.7)'
            }
          }}
          pointOptions={{
            size: 20,
            color: 'rgba(250, 50, 20, 0.7)',
            shape: 'square'
          }}
          textOptions={{
            fontFamily: 'Kaiti SC',
            color: '#f00',
            offset: [0, -20]
          }}
          animationOptions={{
            width: 2,
            color: () => 'rgba(250, 250, 20, 0.7)',
            interval: 0.1
          }}
          data={[
            {
              from: {
                city: '北京'
              },
              to: {
                city: '南京'
              }
            },
            {
              color: '#392',
              from: {
                city: '北京',
              },
              to: {
                name: '哈哈',
                point: {
                  lng: 101.45934,
                  lat: 39.135305
                }
              }
            },
            {
              from: {
                city: '北京'
              },
              to: {
                city: '成都'
              }
            },
            {
              from: {
                city: '北京'
              },
              to: {
                city: '广州'
              }
            }
          ]}
        />`

![image](https://user-images.githubusercontent.com/12874077/104305849-2c85d600-5508-11eb-846f-058b97abad68.png)

**Comment by Junior2Ran** [comment]
看下有什么报错吗

**Comment by Junior2Ran** [comment]
最新版本已修复
