### ISSUE TITLE
使用setMapStyleV2左右拖动白屏

### ISSUE THREAD

**Issue by proto1994** [huiyan-fe/react-bmapgl#13]
使用BMapGL 自定义setMapStyleV2时，在IE11 & chrome 81 等高版本时候拖动会白屏，请问下现在有解决方案吗？

**Comment by proto1994** [comment]
![image](https://user-images.githubusercontent.com/12874077/106145598-b55f6b80-61b0-11eb-8648-b3fafd2f8994.png)

https://maponline2.bdimg.com/tile/?qt=vtile&x=3&y=3&z=5&styleId=undefined&styles=pl&udt=20210126&scaler=1&showtext=0

**Comment by Junior2Ran** [comment]
这个请求url看起来也不太对，方便提供下代码吗

**Comment by proto1994** [comment]
代码现在还不方便提供，我试了下，你用windows上浏览器随便打开一个自定义样式的GL版本的地图，拖动都会有这种问题

**Comment by xiaoxiaocao** [comment]
请教楼主白屏的问题解决了吗？怎么解决的？
