### ISSUE TITLE
获得点标注的图片报 but only one is allowed. 重复跨域问题

### ISSUE THREAD

**Issue by ffffffllllll** [huiyan-fe/react-bmapgl#15]
报错：Access to image at 'http://huiyan.baidu.com/cms/react-bmap/markers_new2x_fbb9e99.png' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, *', but only one is allowed.

![image](https://user-images.githubusercontent.com/18182677/111067520-aa159480-84ff-11eb-8f70-54f92442e7d3.png)

**Comment by Junior2Ran** [comment]
跨域问题已修复

**Comment by ffffffllllll** [comment]
目前还存在这个问题，是没有更新上去吗？还是怎么

**Comment by Junior2Ran** [comment]
更新下版本，0.1.9
