### ISSUE TITLE
请问react-bmapgl中怎么设置标记点跳动？

### ISSUE THREAD

**Issue by Kang127** [huiyan-fe/react-bmapgl#2]
react-bmapgl中要设置类似marker.setAnimation(BMAP_ANIMATION_BOUNCE);的效果，请问这个怎么设置

**Comment by Junior2Ran** [comment]
测试了下原生GL版JSAPI暂无该功能，我们补齐一下该功能，然后在新版本中发布

**Comment by Kang127** [comment]
Marker中的icon怎么显示一个图片？@Junior2Ran

**Comment by Junior2Ran** [comment]
```
<Marker
      position={position}
      icon={icon}
/>
```
详细的文档里有写，icon可以传已有的string类型，也可以自己传一个BMapGL.Icon对象

**Comment by Kang127** [comment]
恩，可以了
<Map {...getMapOption}>
                            <Marker
                                position={{ lng: checkSite.b_longitude, lat: checkSite.b_latitude }}
                                autoViewport={true}
                                icon={new BMapGL.Icon("/image/enterpriseMonitoring/green.png", new BMapGL.Size(40, 67))}
                            />
                        </Map>

**Comment by leleccccc** [comment]
刚好我也需要这个效果
