### ISSUE TITLE
离开使用地图的页面后，移动鼠标就报错

### ISSUE THREAD

**Issue by Rile14929** [huiyan-fe/react-bmapgl#23]
离开使用地图的页面后，移动鼠标就报错
react-bmapgl 版本是0.1.25
![image](https://user-images.githubusercontent.com/30564620/128582409-2147d3c8-fd47-4499-9749-b4a715118d47.png)

**Comment by clarkkentzh** [comment]
我也是

**Comment by Junior2Ran** [comment]
已知问题，在修复了
