### ISSUE TITLE
result 读取报错

### ISSUE THREAD

**Issue by chenshuox** [huiyan-fe/react-bmapgl#28]
Uncaught TypeError: Cannot read properties of undefined (reading 'result')

![image](https://user-images.githubusercontent.com/7846898/138817766-f5b9ac0d-6492-4273-8916-4affde7aca73.png)

**Comment by Junior2Ran** [comment]
地图引擎bug，已经修改，上线中

**Comment by krmao** [comment]
还在发布吗？ @Junior2Ran  [https://lbsyun.baidu.com/jsdemo.htm#aAsynLoadMap](https://lbsyun.baidu.com/jsdemo.htm#aAsynLoadMap) 依然看不到地图

**Comment by krmao** [comment]
![image](https://user-images.githubusercontent.com/7344437/140022967-1c70ee7e-3d64-4a15-a6df-653a13df579e.png)

依然有问题哦，能给个临时的解决方案吗？ @Junior2Ran

**Comment by chenshuox** [comment]
> ![image](https://user-images.githubusercontent.com/7344437/140022967-1c70ee7e-3d64-4a15-a6df-653a13df579e.png)
> 
> 依然有问题哦，能给个临时的解决方案吗？ @Junior2Ran

临时解决方案就是换高德 [😏]
