### ISSUE TITLE
最新版本引入报错

### ISSUE THREAD

**Issue by KarenQiao** [huiyan-fe/react-bmapgl#39]
版本号

"react-bmapgl": "^0.1.28"

![image](https://user-images.githubusercontent.com/27947842/149706534-addc0689-416a-4068-9788-b12601a579b7.png)

![image](https://user-images.githubusercontent.com/27947842/149706668-671b3f3b-b25c-4404-b698-9eb37c29e2fc.png)

**Comment by cl1107** [comment]
+1

**Comment by cl1107** [comment]
> +1

我这边找到原因了，是因为window.define有值导致百度地图走了 amd加载的方式导致的，我在百度地图加载前把window.define设置为null，就可以了，然后在百度地图加载完成后在把 window.define设置回去。你也可以看看是不是这个原因引起的
