### ISSUE TITLE
怎样使用MapvglLayer MapVGL的IconLayer？

### ISSUE THREAD

**Issue by lilicoder** [huiyan-fe/react-bmapgl#4]
想使用MapVGL中的IconLayer.自定义icon

**Comment by Junior2Ran** [comment]
iconlayer的使用文档 https://mapv.baidu.com/gl/docs/IconLayer.html

**Comment by lilicoder** [comment]
@Junior2Ran 您这边有selectedIcon的情况吗？我看只有选中颜色，没有选中图标。您这边怎么处理的呢

**Comment by Junior2Ran** [comment]
上面使用文档里有选中的使用方法，react-bmapgl里只是把mapvgl包了一层，可以写成
```
<MapvglLayer 
  type="IconLayer"
  options={{
    icon: 'your url',
    enablePicked: true,
    autoSelect: true,
    onClick: e => {console.log(e)}
  }}
/>
```

**Comment by lilicoder** [comment]
嗯，IconLayer文档提供了selectedColor参数。如果要展示选中图标的话只能定义pick事件吗

**Comment by Junior2Ran** [comment]
不太明白您说的选中图标和selectColor的区别

**Comment by lilicoder** [comment]
icon1在click或mouseover时更换为icon2这种

**Comment by Junior2Ran** [comment]
监听mousemove事件，dataIndex不为-1时找到选中的数据，修改数据中icon的参数，layer重新setData

**Comment by lilicoder** [comment]
好的 谢谢
