### ISSUE TITLE
setBounds方法限制地图区域不生效

### ISSUE THREAD

**Issue by htyaw** [huiyan-fe/react-bmapgl#40]
`const bounds = new window.BMapGL.Bounds(
      new window.BMapGL.Point(79.031845, 23.07253),
      new window.BMapGL.Point(139.522157, 58.525824),
    );
    map.setBounds(bounds);`

**Comment by ligaofeng0901** [comment]
试试`map.restrictBounds(bounds)`

**Comment by htyaw** [comment]
> 

谢谢 刚才试了一下这个方法可以
