### ISSUE TITLE
Marker点击切换icon颜色不生效

### ISSUE THREAD

**Issue by viviya6** [huiyan-fe/react-bmapgl#5]
{markerList.map((item, index) =>
              <>
                <Marker position={item.position} icon={ currentId === item.id ? 'loc_red' : 'simple_blue'} autoViewport onClick={() => this.iconClick(item)} id={item.id}
                  onMouseover={() => this.setState({ hoverPosition: item.position })}
                />
遍历渲染页面上的marker,根据currentId改变当前icon颜色，现在currentId数据更新了，可是页面render没有触发

**Comment by viviya6** [comment]
[
![Uploading image.png…]()
](url)

**Comment by Junior2Ran** [comment]
抱歉这么久回复。
问题不在该组件库，需要修改判断条件，用state。
this.iconClick函数内的逻辑应该调用setState才会触发页面重新render
