### ISSUE TITLE
Uncaught ReferenceError: BMapGL is not defined

### ISSUE THREAD

**Issue by Julycc41** [huiyan-fe/react-bmapgl#50]
react-bmapgl 下载完后, 
html 存放<script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=1XjLLEhZhQNUzd93EjU5nOGQ"></script>
statr后 一直报这个错 请问是什么情况呢
![1657011841358](https://user-images.githubusercontent.com/80231740/177292154-3e083b38-1c61-4ed5-9bde-b3caa440d58f.png)
![1657011866994](https://user-images.githubusercontent.com/80231740/177292249-ead89375-8070-4149-aa10-b11654bf0328.png)
![1657011886700](https://user-images.githubusercontent.com/80231740/177292335-fc9865de-1459-41e9-9c73-128281495fdc.png)

**Comment by Junior2Ran** [comment]
上面script加载的是2d地图的JSAPI
如果要用webgl地图，请加载webgl地图的JSAPI，如果要用2d地图，请用react-bmap
