### ISSUE TITLE
`types` field in package.json should be `dist/index.d.ts`

### ISSUE THREAD

**Issue by yifanwww** [huiyan-fe/react-bmapgl#55]
Currently the `types` field targets to `types/bmapgl/index.d.ts` where defines GL JSAPI types in `BMapGL` namespace. There is a problem when we import this package:

![image](https://user-images.githubusercontent.com/55199350/182667062-2814ea90-d12a-4468-ac12-1408eeedf653.png)

Because of the `types` field, TypeScript can only find the `BMapGL` namespace in this package, all the types from the src are not exposed.

I think the `types` field should be `dist/index.d.ts` (not the previous `dist/types/index.d.ts`). If users complain they cannot get the type declarations for `BMapGL`, they should install `@types/bmapgl`.

This [doc](https://github.com/huiyan-fe/react-bmapgl/tree/master/types#readme) in this repo talks about the relations between `types/bmapgl` and `@types/bmapgl`. Users can just get `BMapGL` type definitions from `@types/bmapgl`, not from this project.

**Comment by Jinxishihenian** [comment]
https://github.com/huiyan-fe/react-bmapgl/issues/55
