### ISSUE TITLE
使用百度地图组件 开启3D模式 center 不更新

### ISSUE THREAD

**Issue by captain100** [huiyan-fe/react-bmapgl#8]
```js
 return (
    <Map
      style={{ height: '100%', width: '100%' }}
      center={{ lng, lat }}
      heading={heading}  // 开启地图转角
      zoom={19} 
      tilt={70} // 开启地图倾斜角度
    ></Map>
  );
```

连续更新 center 的坐标 地图中心点不更新

https://user-images.githubusercontent.com/8043135/102867022-176ed780-4473-11eb-93bb-dbc068e5dbea.mov

关闭中心点移动效果

https://user-images.githubusercontent.com/8043135/102866492-4f294f80-4472-11eb-96ca-85ae3bbeb50c.mov

**Comment by Junior2Ran** [comment]
方便提供下这两份代码吗

**Comment by Junior2Ran** [comment]
建议把lng和lat改为state属性，这样每次更新数据时会重新render
