### ISSUE TITLE
一直报uncaughtException ReferenceError: md5 is not defined的错误

### ISSUE THREAD

**Issue by hjl2015** [huiyan-fe/react-bmapgl#80]
![image](https://github.com/huiyan-fe/react-bmapgl/assets/13867442/582f5a62-7b9e-472f-bd13-dbb79921de51)

**Comment by jaling530** [comment]
请问解决了吗？我动态引入百度地图url，然后调用BMapGL，也会出现这个。在html直接引入就不会。

**Comment by weixinyi** [comment]
> 请问解决了吗？我动态引入百度地图url，然后调用BMapGL，又出现这个。在html直接引入就不会
解决了吗
