### ISSUE TITLE
vite5.4.0，react版本18.3.1，地图加载完成，瞬间消失

### ISSUE THREAD

**Issue by MshengYang** [huiyan-fe/react-bmapgl#86]
修改源码

<img width="511" alt="image" src="https://github.com/user-attachments/assets/ae79a833-ac3f-4cbc-ac56-2bcc0f184ef7">
移除 this.map.destroy()；显示正常

**Comment by Junior2Ran** [comment]
react开了Strict模式吧？试试关掉strict模式

**Comment by MshengYang** [comment]
> 关掉

正解，关闭了严格模式恢复正常

**Comment by hg3386628** [comment]
有没有保留严格模式的解决方案, 这样太不优雅了
