### ISSUE TITLE
如何离线使用绘图组件

### ISSUE THREAD

**Issue by ReinhardChen93** [huiyan-fe/react-bmapgl#9]
如何离线使用绘图组件
![20201224150845](https://user-images.githubusercontent.com/43949619/103073818-3dc37d00-4603-11eb-8b81-cd198032c7b0.png)
![20201224150614](https://user-images.githubusercontent.com/43949619/103073826-41ef9a80-4603-11eb-82aa-9fdbaa437d5a.png)

**Comment by Junior2Ran** [comment]
把js库离线存下来，然后用script的方式引入即可
